create table users
(
    user_id int generated by default as identity primary key not null,
    username varchar2(20) unique not null,
    password varchar2(12)not null,
    isOnline varchar2(1) not null
);


create table pendingMessages
(
    message_id  int generated by default as identity primary key,
    sender_id   int          not null,
    receiver_id int          not null,
    message     varchar(200) not null,
    foreign key (sender_id) references users (user_id) on delete cascade,
    foreign key (receiver_id) references users (user_id) on delete cascade
);